Dynamic user profiles list
dataiku/dss-plugin-azure-ad-sync pull request #5
Opened 2020-09-24 17:35 UTC by alexbourret

2020-09-28 15:19 UTC, MayeulRousselet requested changes
I think we've misunderstood each other for the user_profile selection. The profile must be the top profile from the subset of the matched groups (ad or dss) for a given user, therefore it is not absolute and must computed per user or better, per group (ad or dss).
Let say we have the following input mapping
```
|   dss_group     |     ad_group    |   profile  |
|         A              |            B           |        C     |
|         A              |             D          |       E      |
```
If an AD user belongs to the groups B&D, then the selected profile must be C (the topmost entry)
If an AD user belongs to the group D, then the selected profile will be E.

What do you think of it?

2020-10-13 09:36 UTC, StanislasGuinel reviewed
I tested it on different edge cases and it works fine.
Only 2 comments and the one I already told you about listing all possible profiles.

2020-10-13 09:36 UTC, StanislasGuinel commented on python-lib/azure_client.py
>              'User "{}" has been created and assigned groups "{}"'.format(user_id, groups)
maybe you could also add the PROFILE the user has been assigned to

2020-11-05 15:03 UTC, MayeulRousselet approved these changes

2020-11-05 15:14 UTC, merged